### ISSUE TITLE
Profile apis should have separate controller 

### ISSUE THREAD

**Issue by mohidkazi** [AritraMaitra/AdonisJsRegistrationAPI#1]
https://github.com/AritraMaitra/AdonisJsRegistrationAPI/blob/89e9688835ce6e79383a59e25554b965f35c9199/start/routes.ts#L27

**Comment by mohidkazi** [comment]
@AritraMaitra 
do not use `AuthController` for every api

`AuthController` should contain foll
- user registration
- user login
- user logout


`ProfileController` should contain foll
- user create profile
- user update profile
- user fetch profile

**Comment by Aritra-Maitra-25** [comment]
Okay done
