### ISSUE TITLE
Create a separate file for validation

### ISSUE THREAD

**Issue by mohidkazi** [AritraMaitra/AdonisJsRegistrationAPI#4]
https://github.com/AritraMaitra/AdonisJsRegistrationAPI/blob/89e9688835ce6e79383a59e25554b965f35c9199/app/Controllers/Http/AuthController.ts#L11

create separate validation file for every validation in the codebase
e,g
- `UserRegistration`
- `UserLogin`
- `UserProfileCreate`
- `UserProfileUpdate`

**Comment by Aritra-Maitra-25** [comment]
implemented
