### ISSUE TITLE
Move Business logic in Service file

### ISSUE THREAD

**Issue by mohidkazi** [AritraMaitra/AdonisJsRegistrationAPI#5]
https://github.com/AritraMaitra/AdonisJsRegistrationAPI/blob/89e9688835ce6e79383a59e25554b965f35c9199/app/Controllers/Http/AuthController.ts#L20

as discussed multiple times before

`Controller` should handle request & response
`Service` should handle business logic

**Comment by Aritra-Maitra-25** [comment]
Implemented
